events {
    worker_connections   1000;
}

http {

    # Inference Server
    server {
        listen       1200;
        listen  [::]:1200;

        location / {
            grpc_pass persongrpcinference:8080;
            client_max_body_size 10G;
        }

        location /person {
            proxy_pass http://personrestinference:8080/person;
            client_max_body_size 1G;
        }
    }

    # Basic Tools
    server {
        listen       1400 ssl;
        listen  [::]:1400 ssl;
        server_name localhost 127.0.0.1;
        ssl_certificate /home/person.crt;
        ssl_certificate_key /home/person.key;

        location /livedemo {
            proxy_pass http://personlivedemo:8080/livedemo;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            client_max_body_size 50M;
        }
    }
}
